-- Persisted immutable canonical schedule and effective-week overlays.
-- Memberships remain the source for student sets; canonical assignments store
-- group/audience semantics, not duplicated student allocations.
begin;

create table if not exists public.canonical_schedule_versions (
  version_id text primary key,
  source_snapshot_id text not null,
  source_fingerprint text not null,
  status text not null check (status in ('draft','approved_baseline','approved_with_exceptions','authoritative','superseded')),
  parent_version_id text references public.canonical_schedule_versions(version_id),
  artifact_schema_version text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  approved_at timestamptz,
  unique(source_snapshot_id, source_fingerprint)
);

create table if not exists public.canonical_schedule_blocks (
  id bigint generated by default as identity primary key,
  version_id text not null references public.canonical_schedule_versions(version_id) on delete restrict,
  block_key text not null,
  weekday integer,
  start_time time,
  end_time time,
  grade_scope text not null default '',
  status text not null,
  mode text not null default '',
  structural_fingerprint text not null default '',
  source_provenance jsonb not null default '{}'::jsonb,
  evidence jsonb not null default '{}'::jsonb,
  unresolved jsonb not null default '[]'::jsonb,
  unique(version_id, block_key)
);

create table if not exists public.canonical_schedule_assignments (
  id bigint generated by default as identity primary key,
  block_id bigint not null references public.canonical_schedule_blocks(id) on delete cascade,
  ordinal integer not null,
  activity text not null default '',
  assignment_kind text not null default 'primary',
  audience_kind text not null default 'canonical_groups',
  canonical_group_ids jsonb not null default '[]'::jsonb,
  source_cells jsonb not null default '[]'::jsonb,
  teacher_ids jsonb not null default '[]'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  unique(block_id, ordinal)
);

create table if not exists public.canonical_effective_weeks (
  effective_week_id text primary key,
  version_id text not null references public.canonical_schedule_versions(version_id) on delete restrict,
  week_start date not null,
  status text not null default 'materialized',
  overlay_source_snapshot_id text,
  provenance jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(version_id, week_start)
);

create table if not exists public.canonical_effective_blocks (
  id bigint generated by default as identity primary key,
  effective_week_id text not null references public.canonical_effective_weeks(effective_week_id) on delete cascade,
  canonical_block_id bigint references public.canonical_schedule_blocks(id) on delete restrict,
  block_key text not null,
  change_kind text not null check (change_kind in ('unchanged','metadata','cancelled','replaced','added','moved','weekly_only')),
  patch jsonb not null default '{}'::jsonb,
  unique(effective_week_id, block_key)
);

create index if not exists canonical_schedule_blocks_version_idx on public.canonical_schedule_blocks(version_id, weekday, start_time);
create index if not exists canonical_effective_blocks_week_idx on public.canonical_effective_blocks(effective_week_id, change_kind);

alter table public.canonical_schedule_versions enable row level security;
alter table public.canonical_schedule_blocks enable row level security;
alter table public.canonical_schedule_assignments enable row level security;
alter table public.canonical_effective_weeks enable row level security;
alter table public.canonical_effective_blocks enable row level security;
revoke all on table public.canonical_schedule_versions, public.canonical_schedule_blocks,
  public.canonical_schedule_assignments, public.canonical_effective_weeks,
  public.canonical_effective_blocks from anon, authenticated;

commit;
